name: "oui-transfer"

services:
  database:
    image: mariadb:11
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  
  server:
    image: node:23
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: 'sh -c "cd /app && npm run start"'